version: '3.7'

volumes:
  mysql-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    environment:
      PHP_XDEBUG_REMOTE_HOST: "host.docker.internal"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mysql
      DB_USERNAME: user
      DB_PASSWORD: secret
      TZ: Asia/Tokyo
    volumes:
      - ./src:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini


  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    platform: linux/x86_64 #M1 Mac向け対応
    ports:
      - "43306:3306"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
